FROM python:3.7-slim

# set environment variables
# ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1


RUN apt update
RUN apt install -y net-tools iputils-ping vim openssh-server

RUN apt install -y poppler-utils

RUN mkdir /packages
WORKDIR /packages

RUN mkdir /root/.ssh; exit 0
COPY minimalkey.pub /root/.ssh/authorized_keys
COPY popplerkey /root/.ssh/id_rsa
RUN chmod 0400 /root/.ssh/id_rsa
COPY ssh_config /root/.ssh/config

#COPY requirements.txt ./
#RUN pip install  -r requirements.txt
#
#COPY poppler-requirements.txt ./
#RUN pip install  -r poppler-requirements.txt

COPY findcopy.sh ./
COPY copy.sh ./
COPY copy_poppler_bins_to_minimal.sh ./

#RUN rm -rf /packages
COPY entrypoint.sh ./
RUN chmod +x ./entrypoint.sh
ENTRYPOINT ["./entrypoint.sh"]

CMD ["/bin/bash"]