FROM python-poppler-dev:latest as base

ENV PYTHONUNBUFFERED 1

RUN apt update && apt install -y postgresql-client

RUN mkdir /packages; exit 0
WORKDIR /packages

COPY poppler-requirements.txt ./
RUN pip install --target=/install -r poppler-requirements.txt

COPY requirements.txt ./
RUN pip install --target=/install -r requirements.txt

COPY copy_pip_packages_to_minimal.sh ./

COPY entrypoint.sh ./
RUN chmod +x ./entrypoint.sh
ENTRYPOINT ["./entrypoint.sh"]

RUN ["/bin/bash"]